name: file_downloader
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^2.0.2
  bot_toast: ^4.0.1
  connectivity_plus: ^1.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0-beta7
  flutter_riverpod: ^0.14.0+3
  flutter_screenutil: 5.0.0-nullsafety.9
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0-nullsafety
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  injectable: ^1.3.0
  intl: ^0.17.0-nullsafety.2
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.0.1
  build_runner: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.1+3
  injectable_generator: ^1.3.0
  json_serializable: ^4.1.1
  pedantic: ^1.11.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100

flutter_intl:
  enabled: true